### ISSUE TITLE
calendar

### ISSUE THREAD

**Issue by desdemonawren** [badfic/phil-bot-java#55]
Phil takes over calendar duties from chronos with RSVP options (Check, X, ?)
Calendar on Phil site for us to add events that go to the swamp
Images?

Time to Kick Chronos to the curb and figure out how to have Phil remind people about events (Or Behrad since he doesn't do much).

We need event creation, Day Before, 30 minutes before, 15 minutes before, and Right At reminder and a way to let people sign up to be reminded so it will @ them specifically when the event happens

**Comment by badfic** [comment]
no longer necessary because of discord events
